AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'src/vendor/**/*'
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
